
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/
    stdin_open: true
    tty: true

  db:
    image: nouchka/sqlite3:latest  # lightweight SQLite container
    container_name: sqlite-db
    volumes:
      - ./
